print(True and True)
print(1==1 and 2==2)
print(False and True)
print("test"=="test")
print(1==1 or 2!=1)
print(1==1 and True)
print(False and 0!=0)
print(True or 1==1)
print("testing"=="testin")
print("test"==1)
print(not(True and False))
print(not(1==1 and 0!=1))
print(not(10 == 1 or 1000==1000))
print(not(1!=10 or 3==4))
print(not("testing"=="testing" and "zed"=="cool guy"))
print(1==1 and (not ("testing"==1 or 1==0)))
print("chunky"=="bacon" and (not(3==4 or 3==3)))
print(3==3 and (not("testing"=="testing" or "python"=="fun")))

